/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as heroHeroImport } from './routes/(hero)/$hero'
import { Route as heroHeroAwardIdImport } from './routes/(hero)/$hero.$awardId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const heroHeroRoute = heroHeroImport.update({
  path: '/$hero',
  getParentRoute: () => rootRoute,
} as any)

const heroHeroAwardIdRoute = heroHeroAwardIdImport.update({
  path: '/$awardId',
  getParentRoute: () => heroHeroRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(hero)/$hero': {
      id: '/$hero'
      path: '/$hero'
      fullPath: '/$hero'
      preLoaderRoute: typeof heroHeroImport
      parentRoute: typeof rootRoute
    }
    '/(hero)/$hero/$awardId': {
      id: '/$hero/$awardId'
      path: '/$awardId'
      fullPath: '/$hero/$awardId'
      preLoaderRoute: typeof heroHeroAwardIdImport
      parentRoute: typeof heroHeroImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  heroHeroRoute: heroHeroRoute.addChildren({ heroHeroAwardIdRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$hero"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/$hero": {
      "filePath": "(hero)/$hero.tsx",
      "children": [
        "/$hero/$awardId"
      ]
    },
    "/$hero/$awardId": {
      "filePath": "(hero)/$hero.$awardId.tsx",
      "parent": "/$hero"
    }
  }
}
ROUTE_MANIFEST_END */
